[package]
name = "rslox"
version = "0.1.0"
authors = ["Sanjeet N. Dasharath <sanjeetdasharath@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# broom = "0.3.0"